In [4]:
import torch # 张量的创建
a = torch.Tensor([[1,2],[2,3]])
print(type(a))#<class 'torch.Tensor'>
a

<class 'torch.Tensor'>


tensor([[1., 2.],
        [2., 3.]])

In [5]:
a = torch.eye(2)
a

tensor([[1., 0.],
        [0., 1.]])

In [6]:
b = torch.zeros(3,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
c = torch.ones(3,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
d = torch.arange(1,10,1) # start end step 左闭右开
d

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
e = torch.linspace(1,10,10) # 使用等差函数创建张量
e

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
f = torch.logspace(1,10,10) # 基数为10 10^1-10^10
f

tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05, 1.0000e+06,
        1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

In [19]:
g = torch.logspace(1,2,10) # 10^1-10^2  num=10
g

tensor([ 10.0000,  12.9155,  16.6810,  21.5443,  27.8256,  35.9381,  46.4159,
         59.9484,  77.4264, 100.0000])

In [20]:
a1 = torch.rand(3,3) # 随机创建张量
a1

tensor([[0.6769, 0.8329, 0.4437],
        [0.6384, 0.4278, 0.3278],
        [0.0111, 0.0607, 0.4535]])

In [21]:
a2 = torch.randn(3,3) # 符合正态分布的张量、均值为0，标准差为1
a2

tensor([[ 0.7874,  0.0771,  2.2083],
        [ 0.0083, -0.7390,  0.0331],
        [-0.7714,  0.0871,  0.4089]])

In [26]:
a3 = torch.randint(1,10,(5,5))
a3

tensor([[4, 2, 2, 9, 2],
        [4, 3, 8, 7, 4],
        [7, 6, 9, 4, 9],
        [3, 5, 9, 3, 7],
        [1, 2, 2, 9, 3]])

In [27]:
import numpy as np
a4 = np.array([1,2])
print(type(a4))
print(a4)

<class 'numpy.ndarray'>
[1 2]


In [28]:
a5 = torch.from_numpy(a4)
print(type(a5))
print(a5)

<class 'torch.Tensor'>
tensor([1, 2], dtype=torch.int32)


In [32]:
a = torch.Tensor(2,3,128,128)
print(a.shape) # torch.Size([2, 3, 128, 128])
print(a[0].shape) # torch.Size([3, 128, 128])
print(a[0][0].shape) # torch.Size([128, 128])
print(a[0][0][0].shape) # torch.Size([128])


torch.Size([2, 3, 128, 128])
torch.Size([3, 128, 128])
torch.Size([128, 128])
torch.Size([128])


In [37]:
a = torch.Tensor(2,3,128,128)
print(a.shape)
print(a[:1,:,:,:].shape) # 取第一张图
print(a[:1,:1,:,:].shape) # 取第一张图的第一个通道
print(a[:1,:1,:64,:64].shape) # torch.Size([1, 1, 64, 64]) 取第一张图的第一个通道的左上四分之一
print(a[:1,:1,:64:2,:64:2].shape) # torch.Size([1, 1, 32, 32])

torch.Size([2, 3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([1, 1, 128, 128])
torch.Size([1, 1, 64, 64])
torch.Size([1, 1, 32, 32])


In [44]:
a = torch.randn(2,3,128,128)
print(a[:1,:1,:1,:1]) 

tensor([[[[2.1203]]]])


In [49]:
a = torch.randn(2,3,128,128) # 使用reshape改变张量
b = a.reshape(2,3,-1)
print(b.shape)
c = a.reshape(4,-1)
print(c.shape) # 24576=(2*3*128*128)/4

torch.Size([2, 3, 16384])
torch.Size([4, 24576])


In [56]:
a = torch.randn(2,3,128,128) # 维度的增加
a = a.unsqueeze(2) # a.unsqueeze(0).shape
a.shape

torch.Size([2, 3, 1, 128, 128])

In [60]:
a = torch.randn(2,3,128,128) # 维度的删减 只能删除大小为一的维度
a = a.squeeze(1)
a.shape

torch.Size([2, 3, 128, 128])

In [63]:
a = torch.randn(2,3,128,128) # 交换维度，且只能交换张量中某两个维度的顺序
a = a.transpose(0,2)
a.shape

torch.Size([128, 3, 2, 128])

In [64]:
a = torch.randn(2,3,128,64) # torch.Size([3, 2, 64, 128]) 多个维度的交换
a = a.permute(1,0,3,2)
a.shape

torch.Size([3, 2, 64, 128])

In [67]:
a = torch.randn(2,1,128,64) # 将一个维度大小为1的维度扩展为其他大小
print(a.shape)
a = a.expand(2,3,128,64)
a.shape

torch.Size([2, 1, 128, 64])


torch.Size([2, 3, 128, 64])