In [1]:
import numpy as np # 导入numpy
a = np.array([[1,2],[3,4]])
a_m = np.matrix([[1,2],[3,4]])
print(type(a))
print(type(a_m))
print(a)
print(a_m)
print(a*a)
print(a_m*a_m)


<class 'numpy.ndarray'>
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [208]:
for x in range(5):
    print(x)

0
1
2
3
4


In [209]:
# 列表生成式 [expression for item in range]
[x+1 for x in range(5)]

[1, 2, 3, 4, 5]

In [211]:
a = [1,2]
b = [2,4]
c = a+b
c

[1, 2, 2, 4]

In [212]:
# 求两个数组相加
def sum(n):
    a = [x+1 for x in range(n)]
    b = [x+1 for x in range(n)]
    new_lst = []
    for i in range(n):
        new_lst.append(a[i]+b[i])
    return new_lst

In [213]:
def numpy_num(n):
    a = np.arange(n) # start stop step [0,1,2,3,4]
    b = np.arange(n)
    a += 1
    b += 1
    return a+b

In [33]:
sum(5)

[2, 4, 6, 8, 10]

In [214]:
numpy_num(5)

array([ 2,  4,  6,  8, 10])

In [219]:
%timeit sum(5000)

1.04 ms ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [220]:
%timeit numpy_num(5000)

19.2 µs ± 905 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [198]:
import numpy as np
np.array
"""
object ： 数组序列
dtype：可选参数、通过它可以更改数组类型
copy：可选，当数据源为ndarray时表示数组能否被复制、默认为True
order：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)
ndmin：可选、用于指定数组的维度
subok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型
"""

'\nobject ： 数组序列\ndtype：可选参数、通过它可以更改数组类型\ncopy：可选，当数据源为ndarray时表示数组能否被复制、默认为True\norder：可选、以哪种内存布局来创建数组、分别为C(行序列)、F(列序列)、A(默认)\nndmin：可选、用于指定数组的维度\nsubok：可选、类型为bool、默认False。当为True时，使用object内部数据类型、为False时、使用数组数据类型\n'

In [206]:
import numpy as np # 创建一维数组
print(np.array((1,2,3)))
print(type(np.array((1,2,3))))
a = np.array([1,2,3])
print(a)
a.ndim

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]


1

In [204]:
import numpy as np # 创建二维数组
a = np.array([[1,2],[3,4]])
a.ndim

2

In [39]:
print(np.array(range(10))) # 生成数组 np.arrange(10)
np.array([1,2,3,4,5,6,7])
print(np.array((1,2,3,4,6,7)))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 6 7]


In [221]:
# 不同类型
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [222]:
np.array([1.2,2.3,3.4,4.5,5.6])
# 思考
np.array([1.2,2.3,3.4,4.5,5.6],dtype=int)  # round(1.5) 

array([1, 2, 3, 4, 5])

In [223]:
int(6.7)

6

In [226]:
round(5.4)

5

In [228]:
a = np.array([1,2,3])
print(a)
b = np.array(a,copy=False)
c = np.array(a,copy=True)
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[1 2 3]
[1 2 3]
[1 2 3]
1623584230256
1623584230256
1623584143472


In [52]:
a = np.array([1,2,3])
c = a.copy()
print(id(a)) #1623558671888
print(id(c))
b = a
print(id(b)) #1623558671888
d = np.array(a)
print(id(d))

1623558671888
1623558671792
1623558671888
1623558669680


In [230]:
a = np.array([1,2,3,4],ndmin=2)
a

array([[1, 2, 3, 4]])

In [61]:
np.arange(10) #0-10 step:1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [232]:
a = np.linspace(1,10,10,dtype=int) # endpoint 是否包含末尾值
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
a = np.logspace(0,9,10,base=2)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [80]:
b = np.logspace(1,2,num=10) # base默认为10
b

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [81]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones(3)

array([1., 1., 1.])

In [85]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [86]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [234]:
# 数组属性
a = np.array([[1,2],[3,4]])
print(a)
a.shape

[[1 2]
 [3 4]]


(2, 2)

In [241]:
a = np.arange(12)
print(a)
a.reshape((3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [243]:
a.resize((3,5),refcheck=False)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  0,  0]])

In [244]:
# 维度
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)

1
2
3
4


In [105]:
# 字节 8bit=1字节 int32 4字节
a = np.array([1,2,3,4])
print(a)
print(a.dtype)
a.itemsize

[1 2 3 4]
int32


4

In [110]:
# 索引和切片
a = np.array(range(10))
print(a[0])
print(a[1:5]) # 左闭右开
print(a[:])
print(a[1:-1:2])

0
[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [117]:
a = np.arange(16).reshape(4,4)
print(a)
print(a[1])
print(a[2][2])
print(a[2:])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[4 5 6 7]
10
[[ 8  9 10 11]
 [12 13 14 15]]


In [121]:
a = np.arange(16).reshape(4,4)
print(a) 
print(a[...,1]) # 在行位置使用...,则代表选取所有行元素，反之则为所有列元素
print(a[...,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [245]:
a = np.arange(16).reshape(4,4)
print(a) 
a[...][1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([4, 5, 6, 7])

In [246]:
a = np.arange(16).reshape(4,4)
print(a) 
b = a[[0,1],[0,1]]
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([0, 5])

In [127]:
# 布尔索引
a = np.arange(10)
a[a>5]

array([6, 7, 8, 9])

In [132]:
# 广播
a = np.arange(12).reshape(3,4)
print(a)
print(b)
b = np.array([1,2,3,4])
c = a+b
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4]


array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [260]:
# 求平均值
a = np.arange(12).reshape(3,4)
print(a)
a.mean(axis=0) # 列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4., 5., 6., 7.])

In [262]:
# 求最大值
a = np.arange(12).reshape(3,4)
print(a)
a.max(axis=0) # 列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 8,  9, 10, 11])

In [263]:
b = np.array([1,2,3,4,5]) # 求中位数
np.median(b)

3.0

In [141]:
b = np.array([1,2,3,4,5])  # 标准差
np.std(b)

1.4142135623730951

In [153]:
# 随机数
np.random.rand(4,2)

array([[0.69596462, 0.15895499],
       [0.24303202, 0.73947226],
       [0.47200932, 0.31803411],
       [0.1614702 , 0.94418661]])

In [157]:
np.random.randn(4,2) # 具有标准正态分布的随机数 均值为0、标准差为1

array([[ 0.46425362, -0.6346284 ],
       [ 0.49483631,  0.29383029],
       [ 0.65112732,  1.56621523],
       [-2.27992794, -0.77440446]])

In [264]:
np.random.randint(-10,10,size=(2,2)) 

array([[-10,  -5],
       [ -5,   1]])

In [267]:
# 随机数种子
np.random.seed(21)
np.random.randn(4,2) 

array([[-0.05196425, -0.11119605],
       [ 1.0417968 , -1.25673929],
       [ 0.74538768, -1.71105376],
       [-0.20586438, -0.23457129]])

In [272]:
# 随机数种子
# np.random.seed(21)
np.random.randn(4,2) 

array([[-0.05196425, -0.11119605],
       [ 1.0417968 , -1.25673929],
       [ 0.74538768, -1.71105376],
       [-0.20586438, -0.23457129]])

In [247]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [249]:
# 添加
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9]],axis=0)) # 添加在每列后面

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [152]:
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9],[6,6,6]],axis=1))  # 添加在行后

[[1 2 3 7 8 9]
 [4 5 6 6 6 6]]


In [250]:
# 插入
a = np.array([1,2,3,4])
print(a)
np.insert(a,3,5)

[1 2 3 4]


array([1, 2, 3, 5, 4])

In [253]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.insert(a,1,6,axis=0)) # 行前进行插入
print(np.insert(a,1,6,axis=1)) # 列前进行插入

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [6 6 6]
 [4 5 6]]
[[1 6 2 3]
 [4 6 5 6]]


In [187]:
# 删除
a = np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,1,axis=1)) #列
print(np.delete(a,1,axis=0)) # 行

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [254]:
# 去重
a = np.array([1,2,3,4,4,4,5,6,7,7])
print(a)
uq = np.unique(a)
print(uq)

[1 2 3 4 4 4 5 6 7 7]
[1 2 3 4 5 6 7]


In [258]:
# 排序
a = np.array([[3,5,7],[4,1,10]])
print(a)
b = np.sort(a,axis=1) # 默认axis=1 按照行排序
b

[[ 3  5  7]
 [ 4  1 10]]


array([[ 3,  5,  7],
       [ 1,  4, 10]])